trigger:
  branches:
    include:
      - main

variables:
  acrName: 'flaskacrsalma'
  acrLoginServer: 'flaskacrsalma.azurecr.io'
  imageName: 'flask-app'
  imageTag: '$(Build.BuildId)'
  appServiceName: 'flask-app-salma'
  resourceGroup: 'flask-rg'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'acr-connection'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        repository: '$(acrLoginServer)/$(imageName)'
        dockerfile: 'Dockerfile'
        tags: |
          $(imageTag)
          latest

    - task: Docker@2
      displayName: 'Push Docker Image to ACR'
      inputs:
        command: push
        repository: '$(acrLoginServer)/$(imageName)'
        containerRegistry: 'acr-connection'
        tags: |
          $(imageTag)
          latest

- stage: Deploy
  displayName: 'Deploy to App Service'
  dependsOn: Build
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: 'azure-connection'
        appName: '$(appServiceName)'
        containers: '$(acrLoginServer)/$(imageName):$(imageTag)'